In [1]:
import pandas as pd
import matplotlib.pyplot as pylot

In [2]:
df = pd.read_csv("positive.csv")
df

Name   Age   Salary  Gender Education     Label
0     John   NaN      NaN    Male  Bachelor  Positive
1     Jane   NaN  60000.0  Female    Master  Positive
2      Bob  30.0      NaN    Male       PhD  Negative
3    Alice  28.0  55000.0  Female       NaN  Negative
4  Charlie  35.0  70000.0     NaN  Bachelor  Positive
5     Dave  32.0  65000.0    Male    Master  Positive
6      Eve  27.0      NaN  Female       PhD  Negative
7    Frank  33.0  75000.0    Male       NaN  Negative
8    Grace  29.0  62000.0  Female    Master  Positive

In [3]:
X = df.iloc[:,:-1].values
y = df.iloc[:,5].values

X

array([['John', nan, nan, 'Male', 'Bachelor'],
       ['Jane', nan, 60000.0, 'Female', 'Master'],
       ['Bob', 30.0, nan, 'Male', 'PhD'],
       ['Alice', 28.0, 55000.0, 'Female', nan],
       ['Charlie', 35.0, 70000.0, nan, 'Bachelor'],
       ['Dave', 32.0, 65000.0, 'Male', 'Master'],
       ['Eve', 27.0, nan, 'Female', 'PhD'],
       ['Frank', 33.0, 75000.0, 'Male', nan],
       ['Grace', 29.0, 62000.0, 'Female', 'Master']], dtype=object)

In [4]:
y

array(['Positive', 'Positive', 'Negative', 'Negative', 'Positive',
       'Positive', 'Negative', 'Negative', 'Positive'], dtype=object)

In [5]:
import numpy as np
from numpy import nan
class Populatevalues:
    def __init__(self, arr, category, column):
        self.arr = arr
        self.category = category
        self.column = column
        self.nanToNone()
        self.Populate()

    def nanToNone(self):
        for row in self.arr:
            for i in range(len(row)):
                if row[i] != row[i]:
                    row[i] = None

    def ifMean(self):
        sum = 0
        count = 0
        num_rows = len(self.arr)
        for i in range(num_rows):
            for j in range(self.column-1, self.column):
                if self.arr[i][j] != None:
                    sum += self.arr[i][j] 
                    count += 1
        mean = sum / count
        return round(mean,1)




    def ifMedian(self):
        count = 0
        new = []
        num_rows = len(self.arr)
        for i in range(num_rows):
            for j in range(self.column-1, self.column):
                if self.arr[i][j] != None:
                    count += 1
                    new.append(self.arr[i][j])
        new = np.sort(new)
        length = len(new)
        if length % 2 == 0:
            median = (length + 1) // 2
        else:
            median = ((length // 2) + ((length + 1) // 2)) // 2
        median_ = new[median]
        return median_
        

    def ifMode(self):
        element_count = {}
        for sublist in self.arr:
            if self.column - 1 < len(sublist):
                element = sublist[self.column-1]
                if element in element_count:
                    element_count[element] += 1
                else:
                    element_count[element] = 1
                    
        most_common_element = None
        max_count = 0
        for element, count in element_count.items():
            if count > max_count:
                most_common_element = element
                max_count = count
                
        return most_common_element

    def Populate(self):
        if self.category == "Mean":
            func = self.ifMean()
        elif self.category == "Median":
            func = self.ifMedian()
        elif self.category == "Mode":
            func = self.ifMode()
            
        for i in range(len(self.arr)):
                for j in range(self.column-1,self.column):
                    if self.arr[i][j] == None:
                        self.arr[i][j] = func



In [6]:
Populatevalues(X,"Mean",2)
Populatevalues(X,"Mean",3)
Populatevalues(X,"Mode",4)
Populatevalues(X,"Mode",5)
X

array([['John', 30.6, 64500.0, 'Male', 'Bachelor'],
       ['Jane', 30.6, 60000.0, 'Female', 'Master'],
       ['Bob', 30.0, 64500.0, 'Male', 'PhD'],
       ['Alice', 28.0, 55000.0, 'Female', 'Master'],
       ['Charlie', 35.0, 70000.0, 'Male', 'Bachelor'],
       ['Dave', 32.0, 65000.0, 'Male', 'Master'],
       ['Eve', 27.0, 64500.0, 'Female', 'PhD'],
       ['Frank', 33.0, 75000.0, 'Male', 'Master'],
       ['Grace', 29.0, 62000.0, 'Female', 'Master']], dtype=object)

In [7]:
import numpy as np
class LabelEncoding:
    def __init__(self,arr,column):
        self.arr = arr
        self.column = column
        self.Encoding()


    def Encoding(self):
        specified_column = self.arr[self.column - 1]
        unique_values = np.unique(specified_column)
        for i in range(len(self.arr)):
            if unique_values[0] == self.arr[i]:
                self.arr[i] = 1
            else:
                self.arr[i] = 0
                

In [8]:
LabelEncoding(y,1)
y


array([1, 1, 0, 0, 1, 1, 0, 0, 1], dtype=object)

In [9]:
import numpy as np

class OneHotEncoder:
    def __init__(self, arr, column):
        self.arr = arr
        self.column = column

    def StrToInt(self):
        specified_column = self.arr[:, self.column - 1]
        unique_values = np.unique(specified_column)
        
        if len(unique_values) == 2:
            for i in range(len(self.arr)):
                if unique_values[0] == self.arr[i][self.column - 1]:
                    self.arr[i][self.column - 1] = 1
                else:
                    self.arr[i][self.column - 1] = 0
        else:
            unique_count = len(unique_values)
            num_rows = self.arr.shape[0]
            new_columns = np.zeros((num_rows, unique_count), dtype=int)
            left_part = self.arr[:, :self.column]
            right_part = self.arr[:, self.column:]
            self.arr = np.concatenate((left_part, new_columns, right_part), axis=1)
            
            for i in range(len(self.arr)):
                for j in range(len(unique_values)):
                    if unique_values[j] == specified_column[i]:
                        self.arr[i][self.column - 1 + j + 1] = 1
            self.arr = np.delete(self.arr, self.column - 1, axis=1)
        return self.arr

In [10]:
encoder = OneHotEncoder(X, 1)
encoded_arr = encoder.StrToInt()
X = encoded_arr
X


array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 30.6, 64500.0, 'Male', 'Bachelor'],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 30.6, 60000.0, 'Female', 'Master'],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 30.0, 64500.0, 'Male', 'PhD'],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 28.0, 55000.0, 'Female', 'Master'],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 35.0, 70000.0, 'Male', 'Bachelor'],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 32.0, 65000.0, 'Male', 'Master'],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 27.0, 64500.0, 'Female', 'PhD'],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 33.0, 75000.0, 'Male', 'Master'],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 29.0, 62000.0, 'Female', 'Master']],
      dtype=object)

In [11]:
encoder = OneHotEncoder(X, 12)
encoded_arr = encoder.StrToInt()
X = encoded_arr

In [12]:
encoder = OneHotEncoder(X, 13)
encoded_arr = encoder.StrToInt()
X = encoded_arr
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 30.6, 64500.0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 30.6, 60000.0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 30.0, 64500.0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 28.0, 55000.0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 35.0, 70000.0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 32.0, 65000.0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 27.0, 64500.0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 33.0, 75000.0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 29.0, 62000.0, 1, 0, 1, 0]],
      dtype=object)

In [13]:
import numpy as np
class Scaling:
    def __init__(self, arr, column, method):
        self.arr = arr
        self.column = column
        self.method = method
        self.Scale()


    def MinMax(self):
        maximum = float(max(self.arr[:, self.column - 1]))
        minimum = float(min(self.arr[:, self.column - 1]))

        for i in range(len(self.arr)):
            for j in range(self.column - 1, self.column):
                self.arr[i][j] = (float(self.arr[i][j]) - minimum) / (maximum - minimum)
            
    def MeanStd (self):
        mean = np.mean(self.arr[:,self.column - 1])
        std = np.std(self.arr[:,self.column - 1])
        for i in range(len(self.arr)):
            for j in range(self.column - 1, self.column):
                self.arr[i][j] = (float(self.arr[i][j]) - mean) / std
        
    def Scale(self):
        if self.method == "MinMax":
            self.MinMax()
        elif self.method == "MeanStd":
            self.MeanStd()


    


In [14]:
Scaling(X,11,"MinMax")
Scaling(X,10,"MeanStd")
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0.009455023062485484, 0.475, 0, 1, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0.009455023062485484, 0.25, 1, 0, 1,
        0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, -0.24583059962458326, 0.475, 0, 0, 0,
        1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, -1.0967826752481438, 0.0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 1.881549589434318, 0.75, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0.6051214759989773, 0.5, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, -1.5222587130599239, 0.475, 1, 0, 0,
        1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 1.0305975138107575, 1.0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, -0.6713066374363635, 0.35, 1, 0, 1, 0]],
      dtype=object)

In [15]:
import numpy as np
class Split:
    def __init__ (self,arr,size):
        self.arr = arr
        self.size = size

    def split(self):
        total = len(self.arr)
        percentage = int((self.size / 100) * total)
        Train = self.arr[:percentage]
        Test = self.arr[percentage:]
        print("Training Data")
        print(Train)
        print("Testing Data")
        print(Test)





In [16]:
s_x = Split(X,70)
s_x.split()



Training Data
[[0 0 0 0 0 0 0 0 1 0.009455023062485484 0.475 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0.009455023062485484 0.25 1 0 1 0]
 [0 1 0 0 0 0 0 0 0 -0.24583059962458326 0.475 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 -1.0967826752481438 0.0 1 0 1 0]
 [0 0 1 0 0 0 0 0 0 1.881549589434318 0.75 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0.6051214759989773 0.5 0 0 1 0]]
Testing Data
[[0 0 0 0 1 0 0 0 0 -1.5222587130599239 0.475 1 0 0 1]
 [0 0 0 0 0 1 0 0 0 1.0305975138107575 1.0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 -0.6713066374363635 0.35 1 0 1 0]]


In [17]:
s_y = Split(y,70)
s_y.split()

Training Data
[1 1 0 0 1 1]
Testing Data
[0 0 1]
